---
version: '3.7'

services:
  code:
    image: ghcr.io/benjaminwood/ben-dev-env:main
    volumes:
      - gems:/gems
      - /var/run/docker.sock:/var/run/docker-host.sock
      - history:/history
    tty: true
    init: true

volumes:
  gems:
  history:
